version: '3.8'

services:
  app-local:
    build:
      context: .
      dockerfile: local.Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
      - KAFKA_URL=kafka:9092
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
    depends_on:
      - kafka-local


  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    command: ./start.sh

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - "22181:2181"

  kafka-local:
    image: bitnami/kafka:latest
    container_name: kafka-local
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT